server:
  port: 8085
db:
  port: 3306
  name: mobilestore_dev
  endpoint: 34.66.234.236
  username: mobilestore.dev
  password: b17m25h19h27

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
url:
  redirect:
    path: ${domain.path}
domain:
  path: http://localhost:3000
