server:
  port: 8085
db:
  port: 3306
  name: mobilestore_fix
  endpoint: 54.254.250.88
  username: mobilestore.dev
  password: Mbs@12345

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
url:
  redirect:
    path: ${domain.path}
domain:
  path: http://localhost:3000
